# -*- coding: utf-8 -*-
"""DepressionIdentifier

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18bEfhQXCtlAies3I4vsf1ZSGvnEtSk7r

# **Depression Identifier (ตัวบ่งชี้ภาวะโรคซึมเศร้า)**

Reference: [Depression Dataset](https://www.kaggle.com/datasets/ikynahidwin/depression-student-dataset)

### **จุดประสงค์**
* เพื่อศึกษาปัจจัยสำคัญที่ทำให้เกิดโรคซึมเศร้า ในช่วงอายุต่างๆ
* สร้างเครื่องมือที่สามารถตรวจโรคซึมเศร้าได้อย่างแม่นยำ
* เพื่อแก้ปัญหาการที่คนคิดไปเองว่าตัวเองเป็นซึมเศร้า
* เพื่อจำแนกอายุที่เป็นโรคซึมเศร้ามากที่สุด

### **สถานการณ์**
* ณ ตอนนี้มีคนไทยจำนวนมากที่สงสัยว่าตัวเองเป็นโรคซึมเศร้า ดังนั้น เครื่องมือนี้จะเป็นประโยชน์อย่างมาก
* โรคซึมเศร้าตอนนี้ จัดเป็นโรคที่ทำให้มีคนเสียชีวิตจากการฆ่าตัวตาย

### **Data Mining**
* เป้าหมายทางธุรกิจ: เพื่อเพิ่มประสิทธิภาพในการวินิจฉัยโรครวมถึงลดระยะเวลาและค่าใช้จ่ายด้านสุขภาพในระยะยาว
* เป้าหมายเชิงเทคนิค: การพัฒนาโมเดล AI ที่มีความแม่นยำสูงและมีค่าความแม่นยำ (accuracy) อย่างน้อย 80%, สร้างกลไกที่สามารถตรวจจับปฏิสัมพันธ์ระหว่างตัวแปรที่ซับซ้อน
ได้โดยใช้เทคนิค feature engineering ที่เหมาะสมเพื่อค้นหารูปแบบที่ซ่อนอยู่

### **แผนดำเนินการ**
* ทำการสำรวจข้อมูลของคน 500 คน ในช่วงอายุ 18-34 ปี แบบสุ่ม โดยติดต่อหน่วยงานที่เกี่ยวข้องกับโรคซึมเศร้า
* สร้างตัวบ่งชี้ภาวะโรคซึมเศร้า โดยใช้ AI
* หากตัวบ่งชี้มีความแม่นยำมากกว่า 80% จะนำตัวบ่งชี้ไปใช้จริง

## **Data Understanding**
"""

# import require library and function
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from sklearn.preprocessing import MinMaxScaler

# make a data frame
data = pd.read_csv('//content/Depression Student Dataset.csv')
data2 = pd.read_csv('//content/Depression Student Dataset.csv')
data

# survey a info
data.info()

data.isna().sum()
# No NaN dtype

data.nunique()

# check duplicated of data depression identifier
data.duplicated().sum()
# no duplicated data

# plot all data
sns.pairplot(data)
plt.show()

"""## **Data Preparation**"""

# check a unique age to seperate a period of ages
pd.unique(data['Age'])

# define an ages seperator and seperate period of ages
def agePeriod(a: int):
  if a <= 22: return 'Early Adulthood'
  elif a <= 26: return 'Middle Adulthood'
  elif a <= 30: return 'Late Adulthood'
  else: return 'Middle Aged'

data['Period of Ages'] = data['Age'].apply(agePeriod)
data2['Period of Ages'] = data2['Age'].apply(agePeriod)
data

# make a count plot for ages and depression
sns.countplot(data,x='Age',hue='Depression')
plt.xticks(rotation=30,ha='right')

# make a count plot for ages and depression to survey the most period of ages has a depression
sns.countplot(data,x='Depression',hue='Age')
plt.xticks(rotation=30,ha='right')



# change depessinon data to int64
data['Depression'] = data['Depression'].map({"Yes":1,"No":0})
data['Have you ever had suicidal thoughts ?'] = data['Have you ever had suicidal thoughts ?'].map({"Yes":1,"No":0})
data = pd.get_dummies(data,dtype=bool)
data

from sklearn.model_selection import train_test_split
trainData = data.drop(['Depression'],axis=1)
target = data['Depression']
inputTrain,inputTest,outputTrain,outputTest = train_test_split(trainData,target,test_size=0.2,random_state=42)
print(inputTrain.shape)
print(inputTest.shape)

"""## **Modeling**"""

from sklearn.tree import plot_tree
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
modelNB = GaussianNB()
modelKN = KNeighborsClassifier()
modelTree = tree.DecisionTreeClassifier()
modelNB.fit(inputTrain,outputTrain)
modelKN.fit(inputTrain,outputTrain)
modelTree.fit(inputTrain,outputTrain)

# decision tree
print(modelTree.classes_)
print(modelTree.feature_importances_)
print(modelTree.get_depth())

"""## **Evaluation**"""

# decision tree evaluation
plt.figure(figsize=(30,20))
plot_tree(modelTree,filled=False)
plt.title("If Decision Tree",fontsize=40)
plt.show()

preTree = modelTree.predict(inputTest)
print(preTree)
preKN = modelKN.predict(inputTest)
print(preKN)
preNB = modelNB.predict(inputTest)
print(preNB)

from sklearn.metrics import accuracy_score,confusion_matrix,ConfusionMatrixDisplay
from sklearn.metrics import classification_report
accTree = accuracy_score(outputTest,preTree)
print(accTree)
accKN = accuracy_score(outputTest,preKN)
print(accKN)
accNB = accuracy_score(outputTest,preNB)
print(accNB)

from sklearn import metrics
print(metrics.classification_report(outputTest,preTree))

l = ['No Depression','Have Depression']
cm = confusion_matrix(outputTest,preTree)
dis = ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=l)
dis.plot()

print(metrics.classification_report(outputTest,preKN))

cm = confusion_matrix(outputTest,preKN)
dis = ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=l)
dis.plot()

print(metrics.classification_report(outputTest,preNB))

cm = confusion_matrix(outputTest,preNB)
dis = ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=l)
dis.plot()

datatmp1 = data2[data2['Period of Ages']=='Early Adulthood']
datatmp2 = data2[data2['Period of Ages']=='Middle Adulthood']
datatmp3 = data2[data2['Period of Ages']=='Late Adulthood']
datatmp4 = data2[data2['Period of Ages']=='Middle Aged']
datatmp1

datatmp2

datatmp3

datatmp4

sns.pairplot(datatmp1)
plt.show()

sns.pairplot(datatmp2)
plt.show()

sns.pairplot(datatmp3)
plt.show()

sns.pairplot(datatmp4)
plt.show()

tmplist = [datatmp1,datatmp2,datatmp3,datatmp4]
tmpl2 = ['18-22 yrs','23-26 yrs','27-30 yrs','30-34 yrs']
for i in range(4):
  plt.title(tmpl2[i],fontsize=20)
  sns.countplot(tmplist[i],x='Study Hours',hue='Depression')
  plt.show()
# 18-22 ชมเรียน

tmplist = [datatmp1,datatmp2,datatmp3,datatmp4]
tmpl2 = ['18-22 yrs','23-26 yrs','27-30 yrs','30-34 yrs']
for i in range(4):
  plt.title(tmpl2[i],fontsize=20)
  sns.countplot(tmplist[i],x='Study Satisfaction',hue='Depression')
  plt.show()
# 23-26 Study Satisfaction

tmplist = [datatmp1,datatmp2,datatmp3,datatmp4]
tmpl2 = ['18-22 yrs','23-26 yrs','27-30 yrs','30-34 yrs']
for i in range(4)
  plt.title(tmpl2[i],fontsize=20)
  sns.countplot(tmplist[i],x='Sleep Hours',hue='Depression')
  plt.show()
  # 27-30 financial stress

tmplist = [datatmp1,datatmp2,datatmp3,datatmp4]
tmpl2 = ['18-22 yrs','23-26 yrs','27-30 yrs','30-34 yrs']
for i in range(4):
  plt.title(tmpl2[i],fontsize=20)
  sns.countplot(tmplist[i],x='Financial Stress',hue='Depression')
  plt.show()
# ไม่ต้อง show, มัน vary (หลากหลาย) มาก